name: 'Build extension and create release'

permissions:
    contents: write

on:
    workflow_dispatch:
    push:
        branches:
            - master
        paths:
            - 'package.json'

jobs:
    compile:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16
                  cache: 'yarn'
            - run: yarn install --frozen-lockfile
            - name: get-version
              id: package-version
              uses: martinbeentjes/npm-get-version-action@main
            - run: yarn run production
            - run: yarn run production:ff
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: 'v${{steps.package-version.outputs.current-version}}'
                  generate_release_notes: true
                  files: |
                      dist/*.zip